platform :ios, '10.0'

use_frameworks!

target 'LoggerWrapper_Example' do
	pod 'LoggerWrapper/CocoaLumberjack', :path => '../'
end

target 'LoggerWrapper_Example-macOS' do
	pod 'LoggerWrapper/CocoaLumberjack', :path => '../'
end
