platform :ios, '9.0'

use_frameworks!

target 'LoggerWrapper_Example' do
	pod 'PluggableApplicationDelegate'
	pod 'LoggerWrapper/CocoaLumberjack/PluggableApplicationDelegate', :path => '../'

  target 'LoggerWrapper_Tests' do
    inherit! :search_paths

    
  end
end
